### PR TITLE
docs

### PR DESCRIPTION
**Pull request by mrsiano**
this patch replace the home.md with readme.md
    in order to make sure we present any content on landing page.
    also i've placed some links to other wiki's.
    we should move on by this approach to have main readme file
    with other wiki links.

### CODE REVIEW

**Comment by abraverm** [comment]
@emarcian, the travis builds are miss configuration on my side, you can ignore them. But I'm a bit lost about all the files and commits.

**Comment by mrsiano** [comment]
@abraverm 
thanks for the help Alex I merged everything into 1 commit see the last PR.

**Comment by mrsiano** [comment]
@ItaySharon @abraverm 
please review

**Review by abraverm — CHANGES_REQUESTED** [review]
The 'Home.md' is the default page in wiki (AFAIK), README.md is only used for repository main page (now wiki) - I think.

**Comment by mrsiano** [comment]
Seems like we can see it nicely only with readme.md
check out my forked project 
https://github.com/mrsiano/rosvr-wiki

**Comment by abraverm** [comment]
Once your document will be merged,  you will see it in https://github.com/RedHat-Israel/rosvr/wiki
just like the readme.md rendered.

**Pull request closed without merging**
